### PR TITLE
CMake now builds on Linux

### PR DESCRIPTION
**Pull request by usernameak**
But please check does it build on Windows or no, I can't check

### CODE REVIEW

**Comment by Corbachu** [comment]
Before I do this -- move your branch to the arranged_source:

https://github.com/3dfxdev/hyper3DGE/tree/arranged_source

And try this all again. I'm nearly finished with it -- which changes some structure to make it easier for platform-independent code. Try this again, and let me know K? =)

Cause even if I merge it into the main branch, eventually arranged_source will be superimposed over it, meaning that we need to be using the source structure from that branch rather than main. Let me know!

**Comment by usernameak** [comment]
@Corbachu okay

**Comment by usernameak** [comment]
@Corbachu i did that, but for some reasons i get blank screen with HUD when I start a level

**Comment by Corbachu** [comment]
That is strange. Are you using -norenderbuffers? And have you disabled GL3 mode? (in console, type 'r_gl3_path 0'. 

Gotta fix that before we do the merge over to the new source structure. ;S

**Comment by usernameak** [comment]
@Corbachu hmm... I didn't know about `-norenderbuffers`
If I use it with GL3 disabled, I see everything, but image looks non-smooth.
If I use norenderbuffers and GL3 enabled, sprites are black.
If I don't use norenderbuffers, everything is black.

**Comment by Corbachu** [comment]
Do you have a video card capable of GLSL? Also, OpenGL 3 mode is not
finished - sprites are black because they do not pass through that
rendering path yet.

Non-smooth image? Have any screenshots?

**Comment by usernameak** [comment]
@Corbachu My video card is capable of GLSL (I don't write from 2001 :D)
About non-smooth image, it looks like it's single-buffered.

**Comment by Corbachu** [comment]
Try doing this, and pull down the console:
r_vsync 0
r_maxfps 0

Vsync is an issue so I usually leave it off, but only because I think the Interpolation code needs serious reworking (you can see how it works currently, mostly handled in /src/n_network.cc.

And about the singe-buffered image -- wonder if triple buffering would work to our advantage. .

**Comment by usernameak** [comment]
@Corbachu nothing changed

**Comment by Corbachu** [comment]
UAK: Did anything change with the 'arranged_source' branch? Please let me know. I want to merge it with the mainline branch ASAP. Thanks! ^^

**Pull request merged**
