### PR TITLE
Compile error fix (error observed on OpenBSD)

### PR DESCRIPTION
**Pull request by ryan-sg**
Originally addressed here: https://github.com/3dfxdev/hyper3DGE/issues/20, this is another attempt to resolve this in a hopefully universally happy way.

I tried just using -fpermissive as gcc seems to throw that flag when it hits the compile error (reprinted here for convenience)  but still no dice:

```
In file included from ddf/../epi/headers.h:26:0,
                 from ddf/../epi/epi.h:22,
                 from ddf/local.h:22,
                 from ddf/main.cc:19:
ddf/main.cc:202:17: error: expected ',' or '...' before numeric constant
  define_c(char *_N, char *_V) : name(_N), value(_V)
                 ^
ddf/main.cc: In constructor 'define_c::define_c(char*)':
ddf/main.cc:202:49: error: '_V' was not declared in this scope
  define_c(char *_N, char *_V) : name(_N), value(_V)
                                                 ^
public:
ddf/main.cc:202:51: warning: invalid conversion from 'int' to 'char*' [-fpermissive]
  define_c(char *_N, char *_V) : name(_N), value(_V)
                                                   ^
ddf/main.cc: In function 'void DDF_MainAddDefine(char*, char*)':
ddf/main.cc:225:40: error: no matching function for call to 'define_c::define_c(char*&, char*&)'
  defines.push_back(define_c(name, value));
                                        ^
ddf/main.cc:225:40: note: candidates are:
ddf/main.cc:202:2: note: define_c::define_c(char*)
  define_c(char *_N, char *_V) : name(_N), value(_V)
  ^
ddf/main.cc:202:2: note:   candidate expects 1 argument, 2 provided
ddf/main.cc:199:2: note: define_c::define_c()
  define_c() : name(NULL), value(NULL)
  ^
ddf/main.cc:199:2: note:   candidate expects 0 arguments, 2 provided
ddf/main.cc:189:7: note: define_c::define_c(const define_c&)
 class define_c
       ^
ddf/main.cc:189:7: note:   candidate expects 1 argument, 2 provided
gmake: *** [Makefiles/Makefile.bsd:133: obj_bsd/ddf/main.o] Error 1
```

Therefore lets remove this underscore entirely and voila, it builds.  I can't seem to find any breakage from this change (or n_N, v_V), but I'll let you guys decide if this is insane or not.  If insane, since _V seems to conflict with a system header here, can we perhaps name them DDF_V and DDF_N?

EDIT: forgot to mention, I did at least try with DDF_V and DDF_N, it still works like that too :-)

### CODE REVIEW

**Comment by ryan-sg** [comment]
hmm, i don't know why those commits from Jun 22 want to be included here, the actual diff is only to one file, i made sure i synced my tree to your master before doing this....git mystery?

**Comment by Corbachu** [comment]
Did we still need to merge this pull?? I don't remember :/

**Comment by ryan-sg** [comment]
Needs something at least, seems to need anything except using the current values of _N and _V respectively.  I am not sure how I feel about just using single character N and V, if you are okay with me setting to DDF_N and DDF_V i'll quickly patch that in and add to this pull request.  Thoughts?

**Comment by Corbachu** [comment]
Could you wrap your changes in a define for BSD specifically? I think that will be the cleanest way of handling it -- thoughts?

**Comment by ryan-sg** [comment]
the last option i just pushed just chooses underscore-prefixed names based after their values.

I don't think this should really require a define for BSD specifically...I think the _V and _N are just symbolic as it is and it shouldn't hurt any other platform.  can we test the build elsewhere with this change and at least verify before introducing a possibly needless ifdef guard?

**Comment by Corbachu** [comment]
Do we still need this one or did we just recently fix this?

**Comment by ryan-sg** [comment]
on my recent build where i reported updates on the two other issues (inertia, sound repeats), i still needed to patch some form of this fix in. (i.e. rename _N and _V to pretty much anything else under the sun, lol)

**Pull request merged**
